# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."syncthing" = {
    image = "lscr.io/linuxserver/syncthing:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Montevideo";
    };
    volumes = [
      "/srv/syncthing/config:/config:rw"
      "/srv/syncthing/data:/data:rw"
    ];
    ports = [
      "8384:8384/tcp"
      "22000:22000/tcp"
      "22000:22000/udp"
      "21027:21027/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=syncthing"
      "--network-alias=syncthing"
      "--network=syncthing_default"
    ];
  };
  systemd.services."podman-syncthing" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-syncthing_default.service"
    ];
    requires = [
      "podman-network-syncthing_default.service"
    ];
    partOf = [
      "podman-compose-syncthing-root.target"
    ];
    wantedBy = [
      "podman-compose-syncthing-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-syncthing_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f syncthing_default";
    };
    script = ''
      podman network inspect syncthing_default || podman network create syncthing_default
    '';
    partOf = [ "podman-compose-syncthing-root.target" ];
    wantedBy = [ "podman-compose-syncthing-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-syncthing-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
